---
- hosts: all
  become: yes
  tasks:
   - name: install web server
     dnf: 
      name: httpd
      state: present

   - name: start webserver on redhat nodes
     service:
       name: httpd
       state: started   